package interpretor;

public enum Type {
	INTEGER, PLUS, MINUS, EOF, MUL,  LPAREN, RPAREN, BEGIN,
	END, DOT, ASSIGN, SEMI, ID, PROGRAM,
	VAR,
	COLON,
	COMMA,
	
	REAL,
	INTEGER_CONST,
	REAL_CONST,
	INTEGER_DIV,
	FLOAT_DIV, NONE, PROCEDURE ;
}
